### ISSUE TITLE
Unable to automate the unlocking of wallet password

### ISSUE THREAD

**Issue by TheTaconator** [xeroc/bitshares-pricefeed#1]
According to the docs for HERO (feedproducer page), the process of using BitShares-PriceFeed can be automated by setting an environment variable UNLOCK with the password for the Uptick wallet.  For example,

```
export UNLOCK=<PasswordHere>
bitshares-pricefeed --configfile=hero.yaml update HERO
```

However, a manual prompt for the password is still requested.

**Comment by iPerky** [comment]
Anyone solved this issue?

**Comment by xeroc** [comment]
There should be an 'unlock' decorator somewhere that doesnt have the UNLOCK environment code .. I have it in uptick but forgot here ..

Ultimately, uptick has a 'customchain' decorator now that can be used to define custom parameters for the BitShares instance.

Not sure when i can find the time to deal with this. Pull request welcome ;)

**Comment by xeroc** [comment]
Fixed this in latest release
